fun main() {
    // Write some code to cause an exception
    val arreglo = IntArray(2)
    print(arreglo[2])
}